/* WrapperFinder v0.1

A replacement Finder for Mac OS 9+ that launches an application using direct calls
to the Macintosh Toolbox and shuts down the OS when the application has been closed.

Designed to be used in conjunction with an emulator to create self-contained applications
that run on modern operating systems without the user being reminded that they are using
an emulator.

***ToolServer Script***
"Macintosh HD:Folder:Folder:Application v1.0" -wait
Shutdown
***********************
- Put above script in a folder in same directory as ToolServer
called "TS Startup Items"
- ToolServer becomes the Finder.
***********************

*/


#include <stdio.h>
#include <string.h>

#include <Files.h>
#include <Processes.h>
#include <ShutDown.h>

char * 					app_path = "Macintosh HD:Infotronapp"; // Path to target application.

FSSpec 					filespec; 		// The file specification generated by File Manager.

LaunchParamBlockRec 	launch_params; 	// Params for LaunchApplication.

ProcessSerialNumber		process_sn; 	// Process serial to be returned by LaunchApplication.

ProcessInfoRec 			process_info; 	// Stores info about the launched process.  Not used,
									  	// but it's a required argument of the function.
									  	
OSErr					process_result;	// The result code received my GetProcessInformation
										// which is used to determine if the application is
										// still running.
										
OSErr 					err;			// Main error handling variable.
